import {AUDIT_AT,places} from './lump-data.js';

const districtPositions={Białołęka:[79,16],Bielany:[40,15],Bemowo:[22,39],Ochota:[43,55],Wola:[39,45],Śródmieście:[55,48],Mokotów:[56,68],Ursynów:[57,83],Włochy:[38,72],Ursus:[22,78],Żoliborz:[51,31],'Praga-Północ':[70,40],'Praga-Południe':[71,62],Targówek:[77,31],Rembertów:[86,61],Wesoła:[91,73]};
const filters=document.querySelector('[data-filters]'),map=document.querySelector('[data-map]'),list=document.querySelector('[data-list]'),panel=document.querySelector('[data-panel]');
let selectedId=null;
let live={updatedAt:null,prices:{},googleHours:{}};

function hash(value){return [...value].reduce((n,char)=>(n*31+char.codePointAt(0))>>>0,7)}
function point(place){const [x,y]=districtPositions[place.district]||[50,50],n=hash(place.id);return {x:x+((n%17)-8)/2,y:y+(((n/17|0)%17)-8)/2}}
function googleUrl(place){return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${place.name}, ${place.address}, Warszawa`)}`}
function priceOf(place){return live.prices?.[place.id]||place.price}
function googleHoursOf(place){return live.googleHours?.[place.id]}
function isConfirmed(place){return place.confidence==='A'&&priceOf(place)!=='N/P'}
function timeWindow(hours){const match=hours.match(/(\d{1,2}):(\d{2})[–-](\d{1,2}):(\d{2})/);if(!match)return null;return [+match[1]*60+ +match[2],+match[3]*60+ +match[4]]}
function isOpen(place){const google=googleHoursOf(place);if(typeof google?.openNow==='boolean')return google.openNow;const range=timeWindow(place.hours);if(!range)return false;const now=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Warsaw',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const values=Object.fromEntries(now.map(part=>[part.type,part.value]));const time=Number(values.hour)*60+Number(values.minute);return time>=range[0]&&time<range[1]}
function filtered(){const data=new FormData(filters),q=String(data.get('q')||'').toLowerCase(),district=String(data.get('district')||''),price=String(data.get('price')||''),confidence=String(data.get('confidence')||''),open=data.get('open')==='on';return places.filter(place=>{const text=`${place.name} ${place.address} ${place.district}`.toLowerCase();const priceMatch=!price||(price==='confirmed'&&isConfirmed(place))||(price==='weight'&&/kg|waga/.test(place.price))||(price==='piece'&&/szt/.test(place.price))||(price==='individual'&&place.price==='indywidualne');return (!q||text.includes(q))&&(!district||place.district===district)&&(!confidence||place.confidence===confidence)&&priceMatch&&(!open||isOpen(place))})}
function drawMap(shown){map.innerHTML='';Object.entries(districtPositions).forEach(([district,[x,y]])=>{const zone=document.createElement('div');zone.className='district';zone.style.left=`${x}%`;zone.style.top=`${y}%`;zone.innerHTML=`<span>${district}</span>`;map.append(zone)});shown.forEach(place=>{const {x,y}=point(place),marker=document.createElement('button');marker.type='button';marker.className=`map-marker${selectedId===place.id?' is-selected':''}`;marker.dataset.confidence=place.confidence;marker.style.left=`${x}%`;marker.style.top=`${y}%`;marker.title=`${place.name}, ${place.address}`;marker.setAttribute('aria-label',marker.title);marker.addEventListener('click',()=>select(place.id));map.append(marker)})}
function placePanel(place){if(!place){panel.innerHTML='<p class="eyebrow">Szczegóły punktu</p><p>Wybierz sklep na mapie lub w tabeli.</p>';return}panel.innerHTML=`<div class="place-panel-grid"><div><p class="eyebrow">${place.district} · źródło ${place.confidence}</p><h3>${place.name}</h3><p>${place.address}, Warszawa</p></div><div><small>Cena</small><strong>${priceOf(place)}</strong></div><div><small>Godziny</small><strong>${googleHoursOf(place)?.weekdayDescriptions?.[0]||place.hours}</strong></div><div><small>Status</small><strong>${isOpen(place)?'Otwarte teraz':'Sprawdź godziny'}</strong></div><a class="button small" href="${googleUrl(place)}" target="_blank" rel="noopener">Google Maps ↗</a></div>`}
function drawList(shown){list.innerHTML=shown.map(place=>`<tr data-id="${place.id}" class="${selectedId===place.id?'is-selected':''}"><td><span class="store-name">${place.name}</span><span class="store-address">${place.address}</span></td><td>${place.district}</td><td>${priceOf(place)}</td><td>${place.hours}</td><td><span class="source-badge ${place.confidence.toLowerCase()}" title="Wiarygodność źródła ${place.confidence}">${place.confidence}</span></td><td><a class="map-link" href="${googleUrl(place)}" target="_blank" rel="noopener">Google ↗</a></td></tr>`).join('');list.querySelectorAll('tr').forEach(row=>row.addEventListener('click',event=>{if(event.target.closest('a'))return;select(row.dataset.id)}))}
function render(){const shown=filtered();drawMap(shown);drawList(shown);placePanel(places.find(place=>place.id===selectedId));document.querySelector('[data-count]').textContent=`${shown.length} z ${places.length} punktów`;document.querySelector('[data-clear]').hidden=!selectedId}
function select(id){selectedId=id;render();panel.scrollIntoView({behavior:'smooth',block:'nearest'})}

for(const district of [...new Set(places.map(place=>place.district))].sort((a,b)=>a.localeCompare(b,'pl'))){filters.elements.district.add(new Option(district,district))}
filters.addEventListener('input',render);document.querySelector('[data-clear]').addEventListener('click',()=>{selectedId=null;render()});
document.querySelector('[data-total]').textContent=places.length;document.querySelector('[data-audit-date]').textContent=new Intl.DateTimeFormat('pl-PL',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(AUDIT_AT));
fetch('./lump-live.json',{cache:'no-store'}).then(response=>response.ok?response.json():null).then(payload=>{if(payload)live={...live,...payload};document.querySelector('[data-confirmed]').textContent=places.filter(isConfirmed).length;render()}).catch(()=>{document.querySelector('[data-confirmed]').textContent=places.filter(isConfirmed).length;render()});
