import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const pages=['index.html','shop.html','pair.html','finder.html','archive.html','guides.html','how-to-measure-jeans-flat.html','jeans-waist-size-vs-flat-measurement.html','jeans-fit-silhouette-guide.html'];
for(const page of pages){
  const html=readFileSync(new URL(page,import.meta.url),'utf8');
  assert.match(html,/<html lang="en">/,`${page} must remain English`);
  assert.match(html,/storefront\.css/,`${page} must use storefront styles`);
  assert.match(html,/storefront\.js/,`${page} must use the shared storefront app`);
}

const home=readFileSync(new URL('index.html',import.meta.url),'utf8');
assert.match(home,/data-limit="5"/,'home must request five pairs');
assert.match(home,/Measured &middot; checked &middot; worn well/i,'home must use the approved brand line');
assert.equal((home.match(/class="hero-img"/g)||[]).length,3,'hero must rotate three images');
assert.match(home,/Sweden, Denmark, Finland/,'shipping countries section must be restored');
assert.match(home,/hero-message-cycle[\s\S]*Find the pair<\/span><span>that already fits<\/span><span>your life\.<\/span>[\s\S]*fadewell-lockup\.png/,'hero message must use three fixed lines and alternate with the original lockup');
assert.match(home,/Wardrobe curated by me/i,'home wardrobe label must use approved copy');
assert.match(home,/One promise runs through the whole shop/,'decoded section must use original copy');
assert.match(home,/Real vintage, checked against the tells of reproductions and fakes/,'decoded features must use original copy');
assert.match(home,/buy with Vinted's buyer protection and bundle discounts/,'Vinted section must use original copy');
assert.doesNotMatch(home,/Open the shop|Not on Vinted\?/,'Vinted section must not show old action buttons');

const finder=readFileSync(new URL('finder.html',import.meta.url),'utf8');
assert.doesNotMatch(finder,/<input required/i,'Finder measurements must all be optional');
assert.match(finder,/Enter one measurement or any combination you know\./,'Finder must explain partial measurement matching');
assert.match(finder,/finder-intro[\s\S]*<span>Enter one measurement[\s\S]*<span>We compare only those numbers/,'Finder intro sentences must be separate lines');
assert.match(finder,/finder-instructions[\s\S]*<span>Fasten it[\s\S]*<span>A difference is not automatically bad/,'Finder instructions must be separate lines');
assert.doesNotMatch(finder,/Every result opens a complete Pair File/,'Finder must omit the redundant Pair File sentence');
assert.match(finder,/name="colour"[\s\S]*name="silhouette"/,'Finder must expose colour-family and silhouette facets');
assert.doesNotMatch(finder,/DNA leads; measurements only decode shape when DNA is incomplete/,'Finder must omit internal Silhouette Engine evidence copy');

const app=readFileSync(new URL('storefront.js',import.meta.url),'utf8');
assert.match(app,/Vintage Jeans &amp; Denim\. Measured\. Checked\. Worn well\./,'footer must restore original tagline');
assert.match(app,/Google profile/,'footer must restore original links');
assert.doesNotMatch(app,/Shop on Vinted/,'footer must not include a Shop on Vinted link');
const css=readFileSync(new URL('storefront.css',import.meta.url),'utf8');
assert.match(css,/heroCopyText 10s/,'hero copy and logo must alternate every five seconds');
assert.match(css,/\.hero \.lede,\.decoded-head>p\{font-size:clamp\(16px,1\.8vw,19px\)/,'hero and decoded paragraphs must share the same font size');
assert.match(css,/@keyframes heroCopyText\{0%,38%\{opacity:1\}46%,92%\{opacity:0\}/,'hero message must fade out cleanly');
assert.match(css,/@keyframes heroCopyLogo\{0%,46%\{opacity:0\}54%,86%\{opacity:1\}/,'hero logo must fade in cleanly');
assert.doesNotMatch(css,/@keyframes heroCopy(?:Text|Logo)[^}]*translateX/,'hero alternation must not slide horizontally');
assert.match(css,/\.hero-cycle-logo\{[^}]*left:50%;top:50%;width:min\(108%,620px\)[^}]*translate\(-50%,-50%\)/,'hero logo must be large and centered');
assert.match(css,/@media\(max-width:620px\)\{\.hero-cycle-logo\{width:min\(88vw,520px\);max-width:88vw\}/,'mobile hero logo must stay inside the viewport');
assert.match(app,/fadewell_storefront_products/,'frontend must use the public storefront projection');
assert.match(app,/cache:'no-store'/,'storefront must prefer the live projection without browser caching');
assert.match(app,/Live wardrobe unavailable; using the last published snapshot/,'storefront must retain a safe published fallback');
assert.match(app,/\/pairs\/\$\{encodeURIComponent\(product\.vinted_item_id\)\}\//,'cards must use stable, indexable Pair File URLs');
assert.match(app,/track_fadewell_storefront_event/,'frontend must use the anonymous first-party Supabase funnel');
assert.match(app,/pair_card_click/,'funnel must measure the list-to-Pair transition');
assert.match(app,/vinted_click/,'funnel must measure the Pair-to-Vinted transition');
for(const eventName of ['finder_start','finder_result_click','browse_shop','open_finder','currency_toggle','archive_view','engaged_view','scroll_75','storefront_error'])assert.match(app,new RegExp(eventName),`funnel must measure ${eventName}`);
assert.match(app,/fadewell-internal-traffic/,'owner traffic must be excludable without identifying normal visitors');
assert.doesNotMatch(app,/cookie|session[_-]?id|user[_-]?id|fingerprint/i,'analytics must not introduce visitor identifiers');
assert.doesNotMatch(app,/service[_-]?role/i,'frontend must never contain a service-role credential');
assert.doesNotMatch(app,/select=\*/,'frontend must request an explicit public field allowlist');
assert.match(app,/View & buy on Vinted/,'product pages must hand purchase off to Vinted');
assert.match(app,/product\.available&&!product\.sold/,'Shop and Finder must exclude unavailable or sold pairs');
assert.match(app,/archive\?product\.sold/,'Pair Archive must contain sold pairs');
assert.match(app,/sort\(\(a,b\)=>\(b\.price_pln/,'home must rank by highest price');
assert.match(app,/showPrice:page!==['"]home['"]/,'home cards must hide prices');
assert.doesNotMatch(app,/class="card-measures"/,'product cards must not repeat measurements beneath the title');
assert.doesNotMatch(app,/class="card-meta"/,'product cards must keep the copy area to title and price');
assert.doesNotMatch(app,/condition_label|vinted_category|size_label/,'product UI must not request Vinted condition, category or tagged size');
assert.match(app,/<small>Silhouette<\/small>/,'product page must show the decoded silhouette');
assert.match(app,/<small>Origin<\/small>/,'product page must show DNA origin');
assert.match(app,/<small>Colour<\/small>/,'product page must show the canonical colour story');
assert.match(app,/dna_origin,dna_era,dna_color/,'public query must request the new DNA display fields');
assert.match(app,/api\.nbp\.pl\/api\/exchangerates\/rates\/a\/eur/,'EUR switch must use the official NBP average-rate API');
assert.match(app,/data-gallery-thumbs/,'pair page must use a bounded thumbnail gallery');
assert.match(app,/data-gallery-hero-prev/,'pair gallery must expose previous-photo navigation');
assert.match(app,/data-gallery-hero-next/,'pair gallery must expose next-photo navigation');
assert.match(app,/selectPhoto\(selected-1\)/,'pair gallery must return one photo at a time, including to the first photo');
assert.match(app,/selectPhoto\(selected\+1\)/,'pair gallery must advance one photo at a time');
assert.match(css,/\.pair-hero-photo img\{[^}]*object-fit:contain/,'pair hero photos must never be cropped');
assert.match(css,/body\[data-page="shop"\] \.card-title\{height:2\.4em/,'shop titles must reserve two lines and raise the price');
assert.match(css,/\.card-price\{margin-top:auto/,'shop prices must align at the bottom of equal card bodies');
assert.match(css,/body\[data-page="shop"\] \.card-price\{margin:4px 0 0;padding-top:0\}/,'Shop prices must sit directly below the reserved title space');
assert.match(css,/\.site-footer\{[^}]*margin-top:clamp\(70px,8vw,120px\)/,'footer must have breathing room from page content');
assert.match(css,/\.footer-grid\{[^}]*align-items:center/,'footer links must align with the brand block');
assert.match(app,/populateOptions\(form,'colour',source\.map\(product=>colourProfile\(product\)\.family\)/,'Shop must populate canonical colour families');
assert.match(app,/populateOptions\(form,'silhouette',source\.map\(product=>silhouetteProfile\(product\)\.label\)/,'Shop must use the shared Silhouette Engine');
assert.match(app,/Number\(b\.vinted_item_id\)-Number\(a\.vinted_item_id\)/,'Newest must follow Vinted listing order rather than refresh timestamps');
assert.match(css,/body\[data-page="shop"\] \.filters\{grid-template-columns:minmax\(150px,1\.4fr\) repeat\(5,minmax\(105px,1fr\)\) auto\}/,'desktop Shop filters must fit in one row');
assert.match(css,/@media\(max-width:900px\)\{\.pair-grid\{grid-template-columns:1fr\}/,'pair page must stack into one column on tablet and mobile');
assert.match(app,/String\(value\)\.trim\(\)!==''/,'Finder must compare only filled measurements');

const utilsSource=readFileSync(new URL('storefront-utils.js',import.meta.url),'utf8');
const utils=await import(`data:text/javascript;base64,${Buffer.from(utilsSource).toString('base64')}`);
const listing=`Authentic Levi’s 535-0285 regular fit jeans, carefully checked and hand-measured by me.\nA softly faded everyday pair.\n\nMeasurements, hand-measured flat by me:\nWaist: 40 cm\nRise: 28 cm\nOne-off piece — only one available in this size.\n⭐ 200+ five-star reviews – buy with confidence.\nFast shipping, happy to answer questions.`;
assert.equal(utils.cleanNotes(listing),'A softly faded everyday pair.','description must stop before measurements and closing clause');
assert.equal(utils.cleanNotes('Authentic Lee jeans, carefully checked and measured by me 👖\n\nCondition: Excellent — worn, but no flaws.\nNo stains or repairs.\n\nMeasurements:\nWaist: 43 cm'),'Condition: Excellent — worn, but no flaws.\nNo stains or repairs.','description must preserve the complete honest condition description');
assert.equal(utils.cleanNotes('Condition: Good vintage condition with a repaired hem.\nMeasurements:\nWaist: 43 cm'),'Condition: Good vintage condition with a repaired hem.','a Condition label is public product evidence, not boilerplate');
assert.equal(utils.cleanNotes('An exceptional pair of true vintage Made in USA Levi’s 501s in classic white denim, carefully checked and measured by me.\nA bright, clean 501 with a straight leg.\n\nMeasurements:\nWaist: 40 cm'),'A bright, clean 501 with a straight leg.','any opening by-me clause must be removed');
assert.equal(utils.cleanNotes('Carefully selected and measured by me. The denim has a soft, even fade.\nMeasurements:\nWaist: 40 cm'),'The denim has a soft, even fade.','same-line copy after the opening clause must remain');
assert.match(utils.publicPairNotes({sold:true,description_raw:null}),/not recovered/,'a recovered sold pair must disclose missing condition evidence rather than invent it');
assert.equal(utils.displaySize({title:"Levi's 535 — W30 L30 — Made in UK"}),'W30 L30','size must come from listing text');
assert.equal(utils.displayFit({title:'Regular straight jeans'}),'Straight');
assert.equal(utils.displayFit({title:'Relaxed tapered jeans'}),'Relaxed Tapered');
assert.equal(utils.displaySize({dna_tagged_size:'W36 L32',title:'Jeans W30 L30'}),'W36 L32','DNA size must win over listing text');
assert.equal(utils.displayFit({dna_fit:'Relaxed Tapered',title:'Straight jeans'}),'Relaxed Tapered','DNA fit must win over listing text');
assert.equal(utils.displayOrigin({dna_origin:'USA',dna_era:'1992'}),'Made in USA — 1992');
assert.equal(utils.displayColor({dna_color:'mid blue'}),'Mid Blue');
assert.equal(utils.displayTitle({title:'Levi’s 501 Selvedge White Oak Cone Denim – Mid Blue – W26 (28) L32 Size M – Rare Piece'}),'Levi’s 501 Selvedge White Oak Cone Denim');

assert.deepEqual(utils.colourProfile({dna_color:'black gray acidwash'}),{raw:'black gray acidwash',family:'Grey',tone:'Dark',finish:'Acid Wash',label:'Dark Grey · Acid Wash',source:'DNA'});
assert.equal(utils.colourProfile({dna_color:'dark grey'}).family,'Grey','Gray and Grey must share one canonical family');
assert.equal(utils.silhouetteProfile({dna_fit:'Relaxed Tapered'}).label,'Roomy Top · Tapered Leg');
assert.equal(utils.silhouetteProfile({dna_fit:'Regular Straight'}).label,'Clean Straight');
assert.equal(utils.silhouetteProfile({dna_fit:'Flare'}).label,'Flared');
assert.equal(utils.silhouetteProfile({measurements:{thigh:{cm:30},leg_opening:{cm:17}}}).label,'Tapered Leg','measurements may decode leg shape only when DNA is missing');
assert.equal(utils.silhouetteProfile({dna_fit:'Regular',measurements:{thigh:{cm:30},leg_opening:{cm:17}}}).label,'Regular Tapered','measurements may complete an incomplete DNA fit');

const allHtml=pages.map(page=>readFileSync(new URL(page,import.meta.url),'utf8')).join('\n');
assert.doesNotMatch(allHtml,/<form[^>]+action=/i,'storefront must not implement a checkout form');
assert.match(readFileSync(new URL('pair.html',import.meta.url),'utf8'),/noindex,follow/,'legacy query Pair page must not compete with canonical Pair URLs');
assert.match(home,/application\/ld\+json/,'home must expose organization structured data');
const buildSource=readFileSync(new URL('scripts/build-storefront.mjs',import.meta.url),'utf8');
assert.match(buildSource,/const STATIC_FILES=\['404\.html'/,'production build must publish the dynamic Pair fallback page');
assert.match(buildSource,/createHash\('sha256'\)[\s\S]*storefront\.\$\{/,'production assets must use content fingerprints');
assert.match(buildSource,/how-to-measure-jeans-flat\.html/,'evergreen guides must enter the generated sitemap');
console.log(`PASS: checked ${pages.length} storefront pages, partial Finder input, cleaned pair copy and home contracts`);
